version: '3.8'

services:
  php_laravel_api:
    build:
      context: ./src
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./src:/var/www 
    working_dir: /var/www 
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql_db
    networks:
      - laravel_app_network
    env_file: 
      - ./src/.env 

  mysql_db:
    image: mysql:5.7
    restart: always
    environment: 

      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - mysql_app_data:/var/lib/mysql
      - ./src/database/dumps:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT_HOST:-3306}:3306"
    networks:
      - laravel_app_network
    env_file:
      - ./src/.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql_db
    ports:
      - "${PMA_PORT:-8081}:80"
    environment:
      PMA_HOST: mysql_db
    networks:
      - laravel_app_network

volumes:
  mysql_app_data:

networks:
  laravel_app_network:
    driver: bridge